### ISSUE TITLE
Error occurs while trying to browse data with submitted multiline text

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-data-manager#2]
This is form.md:

```

---
title: A page with a form
form:
    name: contactform
    fields:
        - name: name
          label: Name
          placeholder: Enter your name
          autofocus: on
          autocomplete: on
          type: text
          validate:
            required: true

        - name: email
          label: Email
          placeholder: Enter your email address
          type: text
          validate:
            rule: email
            required: true

        - name: message
          label: Message
          placeholder: Enter your message
          type: textarea
          validate:
            required: true

    buttons:
        - type: submit
          value: Submit

    process:
        - save:
            fileprefix: contact-
            dateformat: Ymd-His-u
            extension: txt
            body: "{% include 'forms/data.txt.twig' %}"
        - message: Thank you from your feedback!

---

# Nice contact form

{% include 'forms/form.html.twig' %}
```

There is no additional configuration of Data Manager and Form plugins.

If multiline message was submitted, then error occurs while trying to browse Contactform data:
![Error](https://cloud.githubusercontent.com/assets/8279974/9874330/2beed434-5bae-11e5-91bd-e33f8ce95013.png)
